/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.hotmail.doljin99;

import java.io.File;
import javax.swing.JFileChooser;
import org.h2.tools.Server;

/**
 *
 * @author dolji
 */
public class AddServerDialog extends javax.swing.JDialog {

    private ServerMan serverMan;

    /**
     * Creates new form AddServerDialog
     *
     * @param parent
     * @param modal
     */
    public AddServerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        init();
    }

    private void init() {
        jTextFieldAddress.setEditable(false);
        setLocationRelativeTo(this);
    }

    /**
     * Get the value of serverMan
     *
     * @return the value of serverMan
     */
    public ServerMan getServerMan() {
        return serverMan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupWhere = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldTcpPassword = new javax.swing.JPasswordField();
        jCheckBoxDaemon = new javax.swing.JCheckBox();
        jCheckBoxAllowOthers = new javax.swing.JCheckBox();
        jCheckBoxIfNotExists = new javax.swing.JCheckBox();
        jButtonBaseDir = new javax.swing.JButton();
        jTextFieldBaseDir = new javax.swing.JTextField();
        jRadioButtonLocal = new javax.swing.JRadioButton();
        jRadioButtonRemote = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDatabase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldRootUser = new javax.swing.JTextField();
        jLabelRootPassword = new javax.swing.JLabel();
        jPasswordFieldRootPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSetStatus = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("tcp 서버 추가");

        jToolBar1.setRollover(true);

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Save16.gif"))); // NOI18N
        jButtonSave.setText("추가");
        jButtonSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSave.setFocusable(false);
        jButtonSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSave);
        jToolBar1.add(jSeparator1);

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Stop16.gif"))); // NOI18N
        jButtonCancel.setText("취소");
        jButtonCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.setFocusable(false);
        jButtonCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCancel);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jLabel4.setText("이름");

        jLabel1.setText("서버");

        jTextFieldAddress.setText("localhost");

        jLabel2.setText("port");

        jLabel3.setText("tcp 패스워드");
        jLabel3.setToolTipText("tcp 패스워드");

        jCheckBoxDaemon.setSelected(true);
        jCheckBoxDaemon.setText("-tcpDaemon");

        jCheckBoxAllowOthers.setSelected(true);
        jCheckBoxAllowOthers.setText("-tcpAllowOthers");

        jCheckBoxIfNotExists.setSelected(true);
        jCheckBoxIfNotExists.setText("-ifNotExists");

        jButtonBaseDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/navigation/Home16.gif"))); // NOI18N
        jButtonBaseDir.setText("base dir");
        jButtonBaseDir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBaseDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaseDirActionPerformed(evt);
            }
        });

        buttonGroupWhere.add(jRadioButtonLocal);
        jRadioButtonLocal.setSelected(true);
        jRadioButtonLocal.setText("local");
        jRadioButtonLocal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonLocalItemStateChanged(evt);
            }
        });

        buttonGroupWhere.add(jRadioButtonRemote);
        jRadioButtonRemote.setText("remote");

        jLabel5.setText("데이터베이스");

        jLabel6.setText("root user");

        jTextFieldRootUser.setText("SA");
        jTextFieldRootUser.setToolTipText("");

        jLabelRootPassword.setText("root 패스워드");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPort)
                            .addComponent(jTextFieldName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBaseDir)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBaseDir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldDatabase)
                            .addComponent(jPasswordFieldTcpPassword)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonLocal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonRemote))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBoxAllowOthers)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxIfNotExists)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxDaemon)))
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRootPassword)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRootUser)
                            .addComponent(jPasswordFieldRootPassword))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonLocal)
                    .addComponent(jRadioButtonRemote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFieldTcpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBaseDir)
                    .addComponent(jTextFieldBaseDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldRootUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRootPassword)
                    .addComponent(jPasswordFieldRootPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAllowOthers)
                    .addComponent(jCheckBoxIfNotExists)
                    .addComponent(jCheckBoxDaemon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextAreaSetStatus.setEditable(false);
        jTextAreaSetStatus.setColumns(20);
        jTextAreaSetStatus.setLineWrap(true);
        jTextAreaSetStatus.setRows(5);
        jTextAreaSetStatus.setTabSize(4);
        jTextAreaSetStatus.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaSetStatus);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        if (serverMan != null) {
            serverMan.setMessage("취소하였습니다.");
        }
        logMessage("취소하였습니다.");
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void logMessage(String msg) {
        jTextAreaSetStatus.append(msg + "\n");
        jTextAreaSetStatus.setCaretPosition(jTextAreaSetStatus.getText().length() - 1);
        jTextAreaSetStatus.validate();
    }

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        addServer();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void addServer() {
        String serverTemp = jTextFieldName.getText();
        String serverName = (serverTemp == null || serverTemp.isEmpty()) ? "localhost" : serverTemp;
        String address = jTextFieldAddress.getText();
        if (address == null || address.isEmpty()) {
            if (jRadioButtonLocal.isSelected()) {
                address = "localhost";
            } else {
                logMessage("remote일 경우 주소는 필수 입력 항목입니다.");
                return;
            }
        }
        String portTemp = jTextFieldPort.getText();
        String port = (portTemp == null || portTemp.isEmpty()) ? "9092" : portTemp;
        String baseDirTemp = jTextFieldBaseDir.getText();
        String baseDir = (baseDirTemp == null || baseDirTemp.isEmpty()) ? "~" : baseDirTemp;
        char[] tcpPasswordTemp = jPasswordFieldTcpPassword.getPassword();
        String tcpPassword = (tcpPasswordTemp == null || tcpPasswordTemp.length <= 0) ? "" : new String(tcpPasswordTemp);
        String rootUserTemp = jTextFieldRootUser.getText();
        String rootUser = (rootUserTemp == null || rootUserTemp.isEmpty()) ? "SA" : rootUserTemp;
        char[] rootPasswordTemp = jPasswordFieldRootPassword.getPassword();
        String rootPassword = (rootPasswordTemp == null || rootPasswordTemp.length <= 0) ? "" : new String(rootPasswordTemp);

        serverMan = new ServerMan(serverName, port);
        serverMan.setLocal(jRadioButtonLocal.isSelected());
        serverMan.setHostAddress(address);
        serverMan.setTcpDaemon(jCheckBoxDaemon.isSelected());
        serverMan.setTcpPassword(tcpPassword);
        serverMan.setBaseDir(baseDir);
        serverMan.setTcpPassword(tcpPassword);
        serverMan.setRootUser(rootUser);
        serverMan.setRootPassword(rootPassword);
        serverMan.setTcpAllowOthers(jCheckBoxAllowOthers.isSelected());
        serverMan.setIfNotExists(jCheckBoxIfNotExists.isSelected());

        Server server = serverMan.createServer();
        logMessage("결과: " + serverMan.getMessage());
        if (server != null) {
            jButtonSave.setEnabled(false);
            jButtonCancel.setEnabled(false);
        }
        if (server == null) {
            logMessage("결과: " + serverMan.getMessage());
            return;
        }
        String databaseName = jTextFieldDatabase.getText();
        if (databaseName != null && !databaseName.isEmpty()) {
            serverMan.addDatabase(jTextFieldDatabase.getText());
        }
    }

    private void jButtonBaseDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaseDirActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setDialogTitle("base dir 선택");
        chooser.setDialogType(JFileChooser.OPEN_DIALOG);
        chooser.showOpenDialog(this);
        File file = chooser.getSelectedFile();
        if (file == null) {
            logMessage("base dir 설정을 취소하였습니다.");
            return;
        }
        jTextFieldBaseDir.setText(file.getAbsolutePath());
    }//GEN-LAST:event_jButtonBaseDirActionPerformed

    private void jRadioButtonLocalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonLocalItemStateChanged
        boolean local = jRadioButtonLocal.isSelected();
        if (local) {
            jTextFieldAddress.setEditable(false);
            jTextFieldAddress.setText("localhost");
        } else {
            jTextFieldAddress.setEditable(true);
            jTextFieldAddress.setText("");
        }
        jButtonBaseDir.setEnabled(local);
        jCheckBoxAllowOthers.setEnabled(local);
        jCheckBoxDaemon.setEnabled(local);
        jCheckBoxIfNotExists.setEnabled(local);
        jTextFieldBaseDir.setEditable(true);
    }//GEN-LAST:event_jRadioButtonLocalItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupWhere;
    private javax.swing.JButton jButtonBaseDir;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxAllowOthers;
    private javax.swing.JCheckBox jCheckBoxDaemon;
    private javax.swing.JCheckBox jCheckBoxIfNotExists;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelRootPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldRootPassword;
    private javax.swing.JPasswordField jPasswordFieldTcpPassword;
    private javax.swing.JRadioButton jRadioButtonLocal;
    private javax.swing.JRadioButton jRadioButtonRemote;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTextArea jTextAreaSetStatus;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldBaseDir;
    private javax.swing.JTextField jTextFieldDatabase;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldRootUser;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
