/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.hotmail.doljin99;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author dolji
 */
public class AddTableDialog extends javax.swing.JDialog {

    private final DatabaseMan databaseMan;
    
    /**
     * Creates new form AddTableDialog
     * @param parent
     * @param modal
     * @param databaseMan
     */
    public AddTableDialog(java.awt.Frame parent, boolean modal, DatabaseMan databaseMan) {
        super(parent, modal);
        initComponents();
        
        this.databaseMan = databaseMan;
        
        init();
    }
    
    private void init() {
        jTextAreaSql.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                enableExecute();
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                enableExecute();
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                enableExecute();
            }            
            void enableExecute() {
                if (jTextAreaSql.getText().length() > 0) {
                    jButtonExecute.setEnabled(true);
                } else {
                    jButtonExecute.setEnabled(false);
                }
            }
        });
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopmenuPaste = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonExecute = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonCancel = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSql = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaStatus = new javax.swing.JTextArea();

        jPopmenuPaste.setText("붙여넣기");
        jPopmenuPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPopmenuPasteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jPopmenuPaste);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("테이블 추가 SQL 작업 창");

        jToolBar1.setRollover(true);

        jButtonExecute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/media/Play16.gif"))); // NOI18N
        jButtonExecute.setText("실행");
        jButtonExecute.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExecute.setEnabled(false);
        jButtonExecute.setFocusable(false);
        jButtonExecute.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecuteActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonExecute);
        jToolBar1.add(jSeparator1);

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Stop16.gif"))); // NOI18N
        jButtonCancel.setText("취소");
        jButtonCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancel.setFocusable(false);
        jButtonCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonCancel);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jTextAreaSql.setColumns(20);
        jTextAreaSql.setLineWrap(true);
        jTextAreaSql.setRows(5);
        jTextAreaSql.setTabSize(4);
        jTextAreaSql.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaSql);

        jSplitPane1.setTopComponent(jScrollPane2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextAreaStatus.setEditable(false);
        jTextAreaStatus.setColumns(20);
        jTextAreaStatus.setLineWrap(true);
        jTextAreaStatus.setRows(5);
        jTextAreaStatus.setTabSize(4);
        jTextAreaStatus.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaStatus);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setBottomComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPopmenuPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPopmenuPasteActionPerformed
        jTextAreaSql.paste();
    }//GEN-LAST:event_jPopmenuPasteActionPerformed

    private void jButtonExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecuteActionPerformed
        Connection connection;
        connection = databaseMan.getConnection();
        if (connection == null) {
            setStatus("connection 실패: " + databaseMan.getJdbcUrl());
            return;
        }
        Statement statement = null;
        try {
            statement = connection.createStatement();
            int count = statement.executeUpdate(jTextAreaSql.getText());
            setStatus(count + " 행 영향을 줌.");
        } catch (SQLException ex) {
            setStatus("error: "+ ex.getLocalizedMessage());
        } finally {
            if (statement != null) {
                try {
                    statement.close();
                } catch (SQLException ex) {
                }
            }
            try {
                connection.close();
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_jButtonExecuteActionPerformed

    private void setStatus(String msg) {
        jTextAreaStatus.append(msg + "\n");
        jTextAreaStatus.setCaretPosition(jTextAreaStatus.getText().length());
        jTextAreaStatus.validate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonExecute;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jPopmenuPaste;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextAreaSql;
    private javax.swing.JTextArea jTextAreaStatus;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
