/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.hotmail.doljin99;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

/**
 *
 * @author dolji
 */
public class HelpDialog extends javax.swing.JDialog {

    private final String title;
    private final String content;

    /**
     * Creates new form HelpDialog
     *
     * @param parent
     * @param modal
     * @param title
     * @param content
     */
    public HelpDialog(java.awt.Frame parent, boolean modal, String title, String content) {
        super(parent, modal);
        initComponents();
        this.title = title;
        this.content = content;

        init();
    }

    private void init() {
        setTitle(title);
        jEditorPaneContent.setContentType("text/html");
        jEditorPaneContent.addHyperlinkListener(new HyperlinkListener() {
            @Override
            public void hyperlinkUpdate(HyperlinkEvent e) {
                if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
                    try {
                        Desktop.getDesktop().browse(e.getURL().toURI());
                    } catch (IOException | URISyntaxException ex) {
                        appendMessage("링크 연결 에러: " + ex.getLocalizedMessage());
                    }
                }
            }
        });
        jEditorPaneContent.setText(content);
        jEditorPaneContent.setCaretPosition(0);
        setSize(800, 900);
    }
    
    private void appendMessage(String msg) {
        jTextAreaMessage.append(msg + "\n");
        jTextAreaMessage.setCaretPosition(jTextAreaMessage.getText().length() - 1);
        jTextAreaMessage.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneContent = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSplitPane1.setDividerLocation(750);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jEditorPaneContent.setEditable(false);
        jScrollPane1.setViewportView(jEditorPaneContent);

        jSplitPane1.setTopComponent(jScrollPane1);

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMessage);

        jSplitPane1.setBottomComponent(jScrollPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPaneContent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextAreaMessage;
    // End of variables declaration//GEN-END:variables
}
