/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.hotmail.doljin99;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author dolji
 */
public class ScheduledBackupLogDialog extends javax.swing.JDialog {

    /**
     * Creates new form ScheduledBackupLogDialog
     * @param parent
     * @param modal
     */
    public ScheduledBackupLogDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        init();
    }

    private void init() {
        setSize(900, 600);
        String filePath = H2ServerAdmin.SCHEDULED_BACKUP_LOG_DIRECTORY + File.separator + H2ServerAdmin.SCHEDULED_BACKUP_LOG_NAME;
        BufferedReader br = null;
        FileReader fileReader = null;
        try {
            fileReader = new FileReader(filePath);
            br = new BufferedReader(fileReader);
            String line;
            while ((line = br.readLine()) != null) {
                jTextAreaLog.append(line + "\n");
            }
            jTextAreaLog.setCaretPosition(0);
            jTextAreaLog.validate();
        } catch (FileNotFoundException ex) {
            setStatus("로그파일 읽기 에러: " + ex.getLocalizedMessage());
        } catch (IOException ex) {
            setStatus("로그파일 읽기 에러: " + ex.getLocalizedMessage());
        } finally {
            if (fileReader != null) {
                try {
                    fileReader.close();
                } catch (IOException ex) {
                }
            }
            if (br != null) {
                try {
                    br.close();
                } catch (IOException ex) {
                }
            }
        }
    }

    private void setStatus(String msg) {
        jTextAreaStatus.append(msg + "\n");
        jTextAreaStatus.setCaretPosition(jTextAreaStatus.getText().length() - 1);
        jTextAreaStatus.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonCopy = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaStatus = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("정기 백업 로그 보기");

        jToolBar1.setRollover(true);

        jButtonCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Copy16.gif"))); // NOI18N
        jButtonCopy.setText("복사");
        jButtonCopy.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCopy.setFocusable(false);
        jButtonCopy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCopyActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCopy);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextAreaLog.setEditable(false);
        jTextAreaLog.setColumns(20);
        jTextAreaLog.setLineWrap(true);
        jTextAreaLog.setRows(5);
        jTextAreaLog.setTabSize(4);
        jTextAreaLog.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaLog);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTextAreaStatus.setColumns(20);
        jTextAreaStatus.setRows(5);
        jScrollPane2.setViewportView(jTextAreaStatus);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCopyActionPerformed
        jTextAreaLog.requestFocus();
        String selected = jTextAreaLog.getSelectedText();
        if (selected == null) {
            jTextAreaLog.selectAll();
        }
        jTextAreaLog.copy();
        setStatus("백업 로그가 클립보드에 복사되었습니다.");
    }//GEN-LAST:event_jButtonCopyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCopy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextArea jTextAreaStatus;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
