/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hotmail.doljin99;

import com.hotmail.doljin99.loginmanager.LoginManager;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author dolji
 */
public class UnblockPane extends javax.swing.JPanel {

    private final LoginManager loginManager;

    /**
     * Creates new form LoginPane
     *
     * @param loginManager
     */
    public UnblockPane(LoginManager loginManager) {
        initComponents();
        this.loginManager = loginManager;
        
        init();
    }

    private void init() {
        jPasswordFieldPassword.setText("");
        jPasswordFieldPassword.validate();
        jPasswordFieldPassword.requestFocus();
        addMouseListener(new ProcessMouse());
    }
    
    class ProcessMouse implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            eventConsume(e);
        }

        @Override
        public void mousePressed(MouseEvent e) {
            eventConsume(e);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            eventConsume(e);
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            eventConsume(e);
        }

        @Override
        public void mouseExited(MouseEvent e) {
            eventConsume(e);
        }
        
        void eventConsume(MouseEvent e) {
            if (e.getSource() instanceof JButton) {
                System.out.println("accessible name: " + ((JButton) e.getSource()).getAccessibleContext().getAccessibleName());
                if (!((JButton) e.getSource()).getAccessibleContext().getAccessibleName().equals("화면 복구")) {
                    System.out.println("consume ");
                    e.consume();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jCheckBoxPassword = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaStatus = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(204, 255, 204));
        jToolBar1.setRollover(true);

        jButtonSave.setBackground(new java.awt.Color(204, 255, 255));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Refresh16.gif"))); // NOI18N
        jButtonSave.setText("화면 복구");
        jButtonSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSave.setFocusable(false);
        jButtonSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSave);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("패스워드");

        jPasswordFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPasswordActionPerformed(evt);
            }
        });

        jCheckBoxPassword.setBackground(new java.awt.Color(204, 255, 204));
        jCheckBoxPassword.setText("보이기");
        jCheckBoxPassword.setEnabled(false);
        jCheckBoxPassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxPasswordItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxPassword)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPassword))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextAreaStatus.setEditable(false);
        jTextAreaStatus.setBackground(new java.awt.Color(204, 255, 204));
        jTextAreaStatus.setColumns(20);
        jTextAreaStatus.setLineWrap(true);
        jTextAreaStatus.setRows(5);
        jTextAreaStatus.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaStatus);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        login();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jPasswordFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordActionPerformed
        if (loginManager.installed()) {
            login();
        }
    }//GEN-LAST:event_jPasswordFieldPasswordActionPerformed

    private void jCheckBoxPasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxPasswordItemStateChanged
        if (jCheckBoxPassword.isSelected()) {
            jPasswordFieldPassword.setEchoChar((char) 0);
        } else {
            jPasswordFieldPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxPasswordItemStateChanged

    private void login() {
        String password = new String(jPasswordFieldPassword.getPassword());
        if (password == null || password.isEmpty()) {
            setStatus("패스워드를 입력하세요.");
            return;
        }
        if (loginManager.login(password)) {
            jPasswordFieldPassword.setText("");
            jPasswordFieldPassword.validate();
            getParent().setVisible(false);
        } else {
            setStatus("패스워드가 틀렸습니다.");
        }
    }

    protected void setStatus(String msg) {
        jTextAreaStatus.append(msg + "\n");
        jTextAreaStatus.setCaretPosition(jTextAreaStatus.getText().length() - 1);
        jTextAreaStatus.validate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaStatus;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
