/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hotmail.doljin99;

import com.hotmail.doljin99.ManageUserDialog.SimpleTableInfo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dolji
 */
public class UserPriviligesJPanel extends javax.swing.JPanel {

    private UserPrivileges userTablePrivileges;
    private ArrayList<SimpleTableInfo> tableList;

    /**
     * Creates new form CatalogPriviligesJPanel
     *
     */
    public UserPriviligesJPanel(ArrayList<ManageUserDialog.SimpleTableInfo> tableList) {
        initComponents();

        this.tableList = tableList;
        init();
    }

    private void init() {        
        DefaultTableModel model = (DefaultTableModel) jTablePrivileges.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        for (int i = 0; i < tableList.size(); i++) {
            SimpleTableInfo table = tableList.get(i);
            row[0] = table.getTableName();
            row[1] = table.getTableType();
            row[2] = false;
            row[3] = false;
            row[4] = false;
            row[5] = false;
            model.addRow(row);
        }
        jTablePrivileges.validate();
    }

    public void setPrivileges(UserPrivileges userTablePrivileges) {
        if (userTablePrivileges == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTablePrivileges.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        for (int i = 0; i < userTablePrivileges.size(); i++) {
            TablePrivileges tablePrivileges = userTablePrivileges.get(i);
            row[0] = tablePrivileges.getTableName();
            row[1] = tablePrivileges.getTableType();
            row[2] = tablePrivileges.isInsertPrivileges();
            row[3] = tablePrivileges.isSelectPrivileges();
            row[4] = tablePrivileges.isUpdatePrivileges();
            row[5] = tablePrivileges.isDeletePrivileges();
            
            model.addRow(row);
        }
        jTablePrivileges.validate();
    }

    public UserPrivileges getUpdatesCatalogPrivileges(String userName) {
        UserPrivileges updataedUserPrivileges = new UserPrivileges(userName);
        for (int i = 0; i < jTablePrivileges.getRowCount(); i++) {
            TablePrivileges tablePrivileges = new TablePrivileges((String) jTablePrivileges.getValueAt(i, 0), (String) jTablePrivileges.getValueAt(i, 1));
            tablePrivileges.setInsertPrivileges((boolean) jTablePrivileges.getValueAt(i, 2));
            tablePrivileges.setSelectPrivileges((boolean) jTablePrivileges.getValueAt(i, 3));
            tablePrivileges.setUpdatePrivileges((boolean) jTablePrivileges.getValueAt(i, 4));
            tablePrivileges.setDeletePrivileges((boolean) jTablePrivileges.getValueAt(i, 5));

            updataedUserPrivileges.add(tablePrivileges);
        }

        return updataedUserPrivileges;
    }

    public void setEnableTablePrivileges(boolean enable) {
        jTablePrivileges.setEnabled(enable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrivileges = new javax.swing.JTable();

        jTablePrivileges.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "테이블명", "테이블 타입", "INSERT", "SELECT", "UPDATE", "DELETE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePrivileges);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePrivileges;
    // End of variables declaration//GEN-END:variables

    void setAllRights(boolean right) {
        if (jTablePrivileges == null) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jTablePrivileges.getModel();
        int rowCount = model.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            jTablePrivileges.setValueAt(right, i, 2);
            jTablePrivileges.setValueAt(right, i, 3);
            jTablePrivileges.setValueAt(right, i, 4);
            jTablePrivileges.setValueAt(right, i, 5);
        }
        jTablePrivileges.validate();
    }
}
